name: Deploy Chess project to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Disable Jekyll on GitHub Pages
        run: echo "" > docs/.nojekyll

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Build site
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # https://github.com/marketplace/actions/github-pages-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
